In [1]:
import pandas as pd
import json
import re
#from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
eval_name = "eval_make_model_aids"
eval_name = "eval_make_model_wildlife"
eval_name = "eval_make_model_bts"
model_name = "make_model_union"
run_name = eval_name + "_model_" + model_name

# load JSONL
records = []
with open("../aircraft_er_predictions/" + run_name + "_predictions_all.tsv") as f:
    for line in f:
        records.append(json.loads(line))

In [3]:
df = pd.DataFrame(records)
print(len(df))
df.head()

397635

,left,right,match,match_confidence
0,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Beech Bonanza 35A/C/D/E/G/...,0,0.999995
1,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Gipps Aero Ga8 Airvan\n,0,0.999995
2,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180\n,0,0.999991
3,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180A/B\n,0,0.999993
4,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 185A/B/C Skywagon\n,0,0.999996

In [4]:
df_raw = pd.read_csv("../data/ditto_aircraft/" + eval_name + "/all_pairs_with_id.txt", sep="," )
print(len(df_raw))
df_raw.head()

397635

,left_id,right_id,left,right
0,AER PEGASO M100,10,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Beech Bonanza 35A/C/D/E/G/...
1,AER PEGASO M100,26,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Gipps Aero Ga8 Airvan
2,AER PEGASO M100,30,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180
3,AER PEGASO M100,31,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180A/B
4,AER PEGASO M100,33,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 185A/B/C Skywagon

In [5]:
df["left_id"] = df_raw["left_id"] 
df["right_id"] = df_raw["right_id"]

In [6]:
df.head()

,left,right,match,match_confidence,left_id,right_id
0,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Beech Bonanza 35A/C/D/E/G/...,0,0.999995,AER PEGASO M100,10
1,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Gipps Aero Ga8 Airvan\n,0,0.999995,AER PEGASO M100,26
2,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180\n,0,0.999991,AER PEGASO M100,30
3,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180A/B\n,0,0.999993,AER PEGASO M100,31
4,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 185A/B/C Skywagon\n,0,0.999996,AER PEGASO M100,33

In [7]:
### ONLY FOR BTS
df["description"] = df["right"].str.extract(
    r"COL\s+description\s+VAL\s*(.*?)(?=\n\s*COL|$)",
    expand=False
)

In [8]:

PAIR_RE = re.compile(r"COL\s+(?P<key>.*?)\s+VAL\s+(?P<val>.*?)(?=\s+COL\s+|$)")

def record_to_kv_list(record: str):
    """Return list like ['make: WACO', 'model: EGC', ...] in original order."""
    s = str(record)
    return [f"{m.group('key').strip()}: {m.group('val').strip()}"
            for m in PAIR_RE.finditer(s)]

In [9]:
# assuming your dataframe is called matches and has columns "left" and "right"
df["left_kv"]  = df["left"].apply(record_to_kv_list)
df["right_kv"] = df["right"].apply(record_to_kv_list)

In [10]:
df_agg = df.groupby("left_id", as_index=False).agg(
    left_count=("left", "count"),
    right_kv_distinct=("right_kv", lambda s: s.dropna().apply(tuple).nunique()),
)

In [11]:
df_joined = df.merge(
    df_agg,
    how="left",
    on=["left_id"],
)

In [12]:
df_joined

,left,right,match,match_confidence,left_id,right_id,description,left_kv,right_kv,left_count,right_kv_distinct
0,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Beech Bonanza 35A/C/D/E/G/...,0,0.999995,AER PEGASO M100,10,Beech Bonanza 35A/C/D/E/G/H/J/K/S/V/ 36A,"[make: AER PEGASO, model: M100]",[description: Beech Bonanza 35A/C/D/E/G/H/J/K/...,245,245
1,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Gipps Aero Ga8 Airvan\n,0,0.999995,AER PEGASO M100,26,Gipps Aero Ga8 Airvan,"[make: AER PEGASO, model: M100]",[description: Gipps Aero Ga8 Airvan],245,245
2,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180\n,0,0.999991,AER PEGASO M100,30,Cessna 180,"[make: AER PEGASO, model: M100]",[description: Cessna 180],245,245
3,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 180A/B\n,0,0.999993,AER PEGASO M100,31,Cessna 180A/B,"[make: AER PEGASO, model: M100]",[description: Cessna 180A/B],245,245
4,COL make VAL AER PEGASO COL model VAL M100,COL description VAL Cessna 185A/B/C Skywagon\n,0,0.999996,AER PEGASO M100,33,Cessna 185A/B/C Skywagon,"[make: AER PEGASO, model: M100]",[description: Cessna 185A/B/C Skywagon],245,245
...,...,...,...,...,...,...,...,...,...,...,...
397630,COL make VAL ZLIN COL model VAL Z526,COL description VAL Airbus Industrie A380-800\n,0,0.999995,ZLIN Z526,882,Airbus Industrie A380-800,"[make: ZLIN, model: Z526]",[description: Airbus Industrie A380-800],245,245
397631,COL make VAL ZLIN COL model VAL Z526,COL description VAL B787-800 Dreamliner\n,0,0.999984,ZLIN Z526,887,B787-800 Dreamliner,"[make: ZLIN, model: Z526]",[description: B787-800 Dreamliner],245,245
397632,COL make VAL ZLIN COL model VAL Z526,COL description VAL Boeing 737-900ER\n,0,0.999996,ZLIN Z526,888,Boeing 737-900ER,"[make: ZLIN, model: Z526]",[description: Boeing 737-900ER],245,245
397633,COL make VAL ZLIN COL model VAL Z526,COL description VAL B787-900 Dreamliner\n,0,0.999984,ZLIN Z526,889,B787-900 Dreamliner,"[make: ZLIN, model: Z526]",[description: B787-900 Dreamliner],245,245
397634,COL make VAL ZLIN COL model VAL Z526,COL description VAL Antonov 225 (6 Engine)\n,0,0.999659,ZLIN Z526,890,Antonov 225 (6 Engine),"[make: ZLIN, model: Z526]",[description: Antonov 225 (6 Engine)],245,245

In [13]:
print('all evaluated potential paris: ', len(df))
df_matches = df[df["match"]==1]
print('matching paris: ', len(df_matches))

all evaluated potential paris:  397635
matching paris:  1223

In [14]:
df_matches.head()

,left,right,match,match_confidence,left_id,right_id,description,left_kv,right_kv
838,COL make VAL AERO COMMANDER COL model VAL 100 ...,COL description VAL Fokker 100\n,1,0.844149,AERO COMMANDER 100,603,Fokker 100,"[make: AERO COMMANDER, model: 100, name: LARK]",[description: Fokker 100]
1111,COL make VAL AERO COMMANDER COL model VAL 1121...,COL description VAL Gulfstream Aerospace G-III...,1,0.441453,AERO COMMANDER 1121,641,Gulfstream Aerospace G-III/G-IV,"[make: AERO COMMANDER, model: 1121, name: COMM...",[description: Gulfstream Aerospace G-III/G-IV]
1293,COL make VAL AERO COMMANDER COL model VAL 200,COL description VAL Raytheon King Air A100\n,1,0.712787,AERO COMMANDER 200,434,Raytheon King Air A100,"[make: AERO COMMANDER, model: 200]",[description: Raytheon King Air A100]
1363,COL make VAL AERO COMMANDER COL model VAL 200,COL description VAL Gulfstream G200\n,1,0.909066,AERO COMMANDER 200,648,Gulfstream G200,"[make: AERO COMMANDER, model: 200]",[description: Gulfstream G200]
1510,COL make VAL AERO COMMANDER COL model VAL 500 ...,COL description VAL Hughes-500/530\n,1,0.896164,AERO COMMANDER 500,355,Hughes-500/530,"[make: AERO COMMANDER, model: 500, name: SHRIKE]",[description: Hughes-500/530]

In [15]:
df_max = (
    df_matches
      .groupby(['right_id'], as_index=False)
      .agg({
          'match_confidence':      "max",
          'left_id':              lambda s: pd.unique(s).tolist(),
      })
      .rename(columns={'match_confidence': 'match_confidence_max', 'left_id': 'left_ids'})
      .assign(left_ids_count=lambda d: d['left_ids'].str.len())
)

In [16]:
df_max

,right_id,match_confidence_max,left_ids,left_ids_count
0,10,0.901109,[BEECH 35],1
1,26,0.968140,"[BAE JETSTREAM 3100, BAE JETSTREAM 4100, SCHEM...",3
2,30,0.999853,"[BAE JETSTREAM 3100, BAE JETSTREAM 4100, CESSN...",5
3,31,0.998872,"[BAE JETSTREAM 3100, BAE JETSTREAM 4100, CESSN...",4
4,33,0.356167,[CESSNA 185],1
...,...,...,...,...
231,882,0.984001,[BAE JETSTREAM 4100],1
232,887,0.988912,[BOEING 787],1
233,888,0.999972,[BOEING 737],1
234,889,0.998535,[BOEING 787],1
235,890,0.997533,"[BAE JETSTREAM 3100, BAE JETSTREAM 4100, CASA ...",9

In [17]:
df_join = df_matches.merge(
    df_max,
    left_on="right_id",
    right_on="right_id",
    how='left'
)
df_join["is_max"] = df_join["match_confidence"]==df_join["match_confidence_max"]

In [18]:
df_join

,left,right,match,match_confidence,left_id,right_id,description,left_kv,right_kv,match_confidence_max,left_ids,left_ids_count,is_max
0,COL make VAL AERO COMMANDER COL model VAL 100 ...,COL description VAL Fokker 100\n,1,0.844149,AERO COMMANDER 100,603,Fokker 100,"[make: AERO COMMANDER, model: 100, name: LARK]",[description: Fokker 100],0.999229,"[AERO COMMANDER 100, BAE JETSTREAM 3100, BAE J...",11,False
1,COL make VAL AERO COMMANDER COL model VAL 1121...,COL description VAL Gulfstream Aerospace G-III...,1,0.441453,AERO COMMANDER 1121,641,Gulfstream Aerospace G-III/G-IV,"[make: AERO COMMANDER, model: 1121, name: COMM...",[description: Gulfstream Aerospace G-III/G-IV],0.998248,"[AERO COMMANDER 1121, AERONCA C2, AMERICAN EAG...",40,False
2,COL make VAL AERO COMMANDER COL model VAL 200,COL description VAL Raytheon King Air A100\n,1,0.712787,AERO COMMANDER 200,434,Raytheon King Air A100,"[make: AERO COMMANDER, model: 200]",[description: Raytheon King Air A100],0.998511,"[AERO COMMANDER 200, AVIAT A1, BAE JETSTREAM 3...",15,False
3,COL make VAL AERO COMMANDER COL model VAL 200,COL description VAL Gulfstream G200\n,1,0.909066,AERO COMMANDER 200,648,Gulfstream G200,"[make: AERO COMMANDER, model: 200]",[description: Gulfstream G200],0.999181,"[AERO COMMANDER 200, BAE JETSTREAM 3100, BAE J...",7,False
4,COL make VAL AERO COMMANDER COL model VAL 500 ...,COL description VAL Hughes-500/530\n,1,0.896164,AERO COMMANDER 500,355,Hughes-500/530,"[make: AERO COMMANDER, model: 500, name: SHRIKE]",[description: Hughes-500/530],0.998958,"[AERO COMMANDER 500, BAE JETSTREAM 3100, BAE J...",8,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,COL make VAL VULTEE COL model VAL V1,COL description VAL Airbus Industrie A-318\n,1,0.357048,VULTEE V1,644,Airbus Industrie A-318,"[make: VULTEE, model: V1]",[description: Airbus Industrie A-318],0.999686,"[AERONCA C2, AGUSTA AW139, AIRBUS A321, AVIAT ...",38,False
1219,COL make VAL WACO COL model VAL CJC,COL description VAL Cessna Citationjet/CJ1/CJ2...,1,0.724677,WACO CJC,639,Cessna Citationjet/CJ1/CJ2/CJ3,"[make: WACO, model: CJC]",[description: Cessna Citationjet/CJ1/CJ2/CJ3],0.992111,"[PIPER J2, PIPER J3, PIPER J3C, WACO CJC]",4,False
1220,COL make VAL YAKOVLEV COL model VAL YAK40,COL description VAL Ilyushiin Il-96-400t\n,1,0.618883,YAKOVLEV YAK40,881,Ilyushiin Il-96-400t,"[make: YAKOVLEV, model: YAK40]",[description: Ilyushiin Il-96-400t],0.999683,"[AERONCA C2, AVIAT A1, BAC ONE ELEVEN, BAE JET...",25,False
1221,COL make VAL ZLIN COL model VAL Z242,COL description VAL Antonov 24/26/32\n,1,0.384459,ZLIN Z242,444,Antonov 24/26/32,"[make: ZLIN, model: Z242]",[description: Antonov 24/26/32],0.998632,"[AEROCAR I, AERONCA C2, BAC ONE ELEVEN, BAE JE...",21,False
1222,COL make VAL ZLIN COL model VAL Z242,COL description VAL Antonov 24/26/32\n,1,0.384459,ZLIN Z242,444,Antonov 24/26/32,"[make: ZLIN, model: Z242]",[description: Antonov 24/26/32],0.998632,"[AEROCAR I, AERONCA C2, BAC ONE ELEVEN, BAE JE...",21,False

In [19]:
df_join.to_csv("../aircraft_er_predictions/" + run_name + "_all_matches.csv", index=False)

In [20]:
df_join_max = df_join[df_join["is_max"]==True]

df_join_max

,left,right,match,match_confidence,left_id,right_id,description,left_kv,right_kv,match_confidence_max,left_ids,left_ids_count,is_max
7,COL make VAL AERO COMMANDER COL model VAL 500 ...,COL description VAL Gulfstream Aerospace G500\n,1,0.999343,AERO COMMANDER 500,749,Gulfstream Aerospace G500,"[make: AERO COMMANDER, model: 500, name: SHRIKE]",[description: Gulfstream Aerospace G500],0.999343,"[AERO COMMANDER 500, BAE JETSTREAM 3100, CESSN...",6,True
8,COL make VAL AERO COMMANDER COL model VAL 695 ...,COL description VAL Bombardier CRJ 705\n,1,0.999569,AERO COMMANDER 695,657,Bombardier CRJ 705,"[make: AERO COMMANDER, model: 695, name: 1000 ...",[description: Bombardier CRJ 705],0.999569,"[AERO COMMANDER 695, BEECH 70, SCHEMPP HIRTH S...",3,True
11,COL make VAL AEROCAR COL model VAL I,COL description VAL Casa/Nurtanio C212 Aviocar\n,1,0.797704,AEROCAR I,412,Casa/Nurtanio C212 Aviocar,"[make: AEROCAR, model: I]",[description: Casa/Nurtanio C212 Aviocar],0.797704,"[AEROCAR I, AERONCA C2, CASA C212, PILATUS B4]",4,True
28,COL make VAL AEROSPATIALE COL model VAL AS350 ...,COL description VAL Eurocompter AS350 B2 AStar\n,1,0.984738,AEROSPATIALE AS350,340,Eurocompter AS350 B2 AStar,"[make: AEROSPATIALE, model: AS350, name: ECURE...",[description: Eurocompter AS350 B2 AStar],0.984738,"[AEROSPATIALE AS350, EUROCOPTER AS350]",2,True
36,COL make VAL AGUSTA COL model VAL AW139,COL description VAL Agustawestland AW139\n,1,0.999948,AGUSTA AW139,393,Agustawestland AW139,"[make: AGUSTA, model: AW139]",[description: Agustawestland AW139],0.999948,"[AGUSTA AW139, BAE JETSTREAM 3100, SCHEMPP HIR...",3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1148,COL make VAL SIKORSKY COL model VAL S76,COL description VAL Sikorsky S-76\n,1,0.999556,SIKORSKY S76,390,Sikorsky S-76,"[make: SIKORSKY, model: S76]",[description: Sikorsky S-76],0.999556,"[SCHEMPP HIRTH STANDARD AUSTRIA, SIKORSKY S76]",2,True
1149,COL make VAL SIKORSKY COL model VAL S76,COL description VAL Sikorsky S-76\n,1,0.999556,SIKORSKY S76,390,Sikorsky S-76,"[make: SIKORSKY, model: S76]",[description: Sikorsky S-76],0.999556,"[SCHEMPP HIRTH STANDARD AUSTRIA, SIKORSKY S76]",2,True
1150,COL make VAL SIKORSKY COL model VAL S76,COL description VAL Sikorsky S-76\n,1,0.999556,SIKORSKY S76,390,Sikorsky S-76,"[make: SIKORSKY, model: S76]",[description: Sikorsky S-76],0.999556,"[SCHEMPP HIRTH STANDARD AUSTRIA, SIKORSKY S76]",2,True
1179,COL make VAL SUD AVIATION COL model VAL SE210 ...,COL description VAL Aerospatiale Caravelle SE-...,1,0.999543,SUD AVIATION SE210,680,Aerospatiale Caravelle SE-210,"[make: SUD AVIATION, model: SE210, name: CARAV...",[description: Aerospatiale Caravelle SE-210],0.999543,"[SCHEMPP HIRTH STANDARD AUSTRIA, SUD AVIATION ...",2,True
1182,COL make VAL TECNAM COL model VAL P2012,COL description VAL P2012 Traveler\n,1,0.999960,TECNAM P2012,102,P2012 Traveler,"[make: TECNAM, model: P2012]",[description: P2012 Traveler],0.999960,"[BAC ONE ELEVEN, SCHEMPP HIRTH STANDARD AUSTRI...",3,True

In [21]:
df_join_max.to_csv('temp.csv')

df_join_max.to_csv("../aircraft_er_predictions/" + run_name + "_max_matches.csv", index=False)

In [22]:
df_matches[df_matches["right"].isna()]

Empty DataFrame
Columns: [left, right, match, match_confidence, left_id, right_id, description, left_kv, right_kv]
Index: []