In [1]:
import pandas as pd
import json
import re
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
run_name = "baseline"
run_name = "baseline_lh"
run_name = "baseline_lh_2"
run_name = "baseline_lh_3"

run_name = "baseline_lh_1"
run_name = "baseline_lh_0"
run_name = "baseline_lh"

run_name = "baseline"

# load JSONL
records = []
with open("../aircraft_er_predictions/" + run_name + "_predictions_all.tsv") as f:
    for line in f:
        records.append(json.loads(line))


        # load JSONL
records_test = []
with open("../aircraft_er_predictions/" + run_name + "_predictions_test.tsv") as f:
    for line in f:
        records_test.append(json.loads(line))

In [3]:
df_all = pd.DataFrame(records)
df_test = pd.DataFrame(records_test)
df_test.head()

,left,right,match,match_confidence
0,COL make VAL BOEING COL model VAL 707 COL seri...,COL make VAL PC COL model VAL 6 COL series VAL...,0,0.999997
1,COL make VAL FAIRCHILD COL model VAL PILGRIM 1...,COL make VAL THNDCT COL model VAL COLT COL ser...,0,0.999996
2,COL make VAL AEROSPATIALE COL model VAL SA330 ...,COL make VAL SA COL model VAL 330 COL series V...,1,0.999919
3,COL make VAL BOEING COL model VAL 727 COL seri...,COL make VAL B COL model VAL 727 COL series VA...,0,0.999984
4,COL make VAL PILATUS COL model VAL PC6 COL ser...,COL make VAL PC COL model VAL 6 COL series VAL...,1,0.999897

In [4]:
gold_test = pd.read_csv("../data/ditto_aircraft/" + run_name + "/test.txt", sep="\t", header=None, names=["left", "right", "gold"])

gold_all = pd.read_csv("../data/ditto_aircraft/" + run_name + "/all_pairs.txt", sep="\t", header=None, names=["left", "right", "gold"])
print(gold_all.head())

                                                left  \
0  COL make VAL GULFSTREAM COL model VAL GVI COL ...
1  COL make VAL PIAGGIO COL model VAL P136 COL se...
2  COL make VAL AERONCA COL model VAL L3 COL seri...
3  COL make VAL PZL OKECIE COL model VAL PZL104 C...
4  COL make VAL BEECH COL model VAL 99 COL series...

                                               right  gold
0  COL make VAL PA COL model VAL 46 COL series VA...     0
1  COL make VAL BHT COL model VAL UH1E COL series...     0
2  COL make VAL LR COL model VAL 45 COL series VA...     0
3  COL make VAL B COL model VAL 737 COL series VA...     0
4  COL make VAL BE COL model VAL 18 COL series VA...     0

In [5]:
df_all["gold"] = gold_all["gold"]
df_test["gold"] = gold_test["gold"]

In [6]:
#Test Data

y_true_test = df_test["gold"]
y_pred_test = df_test["match"]

print("Accuracy:", accuracy_score(y_true_test, y_pred_test))
print("\nClassification report:\n", classification_report(y_true_test, y_pred_test,digits=3))
print("\nConfusion matrix:\n", confusion_matrix(y_true_test, y_pred_test))



with open("../aircraft_er_predictions/" + run_name + "_metrics_test.txt", "w") as f:
    print("Accuracy:", accuracy_score(y_true_test, y_pred_test), file=f)
    print("\nClassification report:\n", file=f)
    print(classification_report(y_true_test, y_pred_test,digits=3), file=f)
    print("\nConfusion matrix:\n", file=f)
    print(confusion_matrix(y_true_test, y_pred_test), file=f)

Accuracy: 0.9980222496909765

Classification report:
               precision    recall  f1-score   support

           0      0.999     0.998     0.999      3677
           1      0.984     0.995     0.989       368

    accuracy                          0.998      4045
   macro avg      0.992     0.996     0.994      4045
weighted avg      0.998     0.998     0.998      4045


Confusion matrix:
 [[3671    6]
 [   2  366]]

In [7]:
#All Data

y_true = df_all["gold"]
y_pred = df_all["match"]

print("Accuracy:", accuracy_score(y_true, y_pred))
print("\nClassification report:\n", classification_report(y_true, y_pred,digits=3))
print("\nConfusion matrix:\n", confusion_matrix(y_true, y_pred))



with open("../aircraft_er_predictions/" + run_name + "_metrics_all.txt", "w") as f:
    print("Accuracy:", accuracy_score(y_true, y_pred), file=f)
    print("\nClassification report:\n", file=f)
    print(classification_report(y_true, y_pred, digits=3), file=f)
    print("\nConfusion matrix:\n", file=f)
    print(confusion_matrix(y_true, y_pred), file=f)

Accuracy: 0.9993067247697336

Classification report:
               precision    recall  f1-score   support

           0      1.000     1.000     1.000     36710
           1      0.996     0.997     0.996      3678

    accuracy                          0.999     40388
   macro avg      0.998     0.998     0.998     40388
weighted avg      0.999     0.999     0.999     40388


Confusion matrix:
 [[36694    16]
 [   12  3666]]

In [8]:
errors = df_test[df_test["gold"] != df_test["match"]]
print(errors[["left","right","gold","match","match_confidence"]].head(20))

                                                   left  \
636   COL make VAL LEARJET COL model VAL 35 COL seri...
1102  COL make VAL BEECH COL model VAL AT10 COL seri...
1713  COL make VAL MITSUBISHI COL model VAL MU2B COL...
1845  COL make VAL BELL COL model VAL UH1 COL series...
2152  COL make VAL AERO DIFUSION COL model VAL D1190...
2962  COL make VAL CESSNA COL model VAL 402 COL seri...
3615  COL make VAL REARWIN COL model VAL 8500 COL se...
3899  COL make VAL HAWKER SIDDELEY COL model VAL HS1...

                                                  right  gold  match  \
636   COL make VAL LR COL model VAL 35 COL series VA...     1      0
1102  COL make VAL VERVLE COL model VAL AT COL serie...     0      1
1713  COL make VAL MU COL model VAL 2B COL series VA...     0      1
1845  COL make VAL FEDRIC COL model VAL UH34 COL ser...     0      1
2152  COL make VAL AMD COL model VAL 50 COL series V...     0      1
2962  COL make VAL CE COL model VAL 401 COL series V...     0      1
3615  COL make VAL COMWTH COL model VAL 9000 COL ser...     1      0
3899  COL make VAL HS COL model VAL 125 COL series V...     0      1

      match_confidence
636           0.999731
1102          0.998443
1713          0.999841
1845          0.870332
2152          0.792658
2962          0.999301
3615          0.999971
3899          0.558602

In [9]:
errors

,left,right,match,match_confidence,gold
636,COL make VAL LEARJET COL model VAL 35 COL seri...,COL make VAL LR COL model VAL 35 COL series VA...,0,0.999731,1
1102,COL make VAL BEECH COL model VAL AT10 COL seri...,COL make VAL VERVLE COL model VAL AT COL serie...,1,0.998443,0
1713,COL make VAL MITSUBISHI COL model VAL MU2B COL...,COL make VAL MU COL model VAL 2B COL series VA...,1,0.999841,0
1845,COL make VAL BELL COL model VAL UH1 COL series...,COL make VAL FEDRIC COL model VAL UH34 COL ser...,1,0.870332,0
2152,COL make VAL AERO DIFUSION COL model VAL D1190...,COL make VAL AMD COL model VAL 50 COL series V...,1,0.792658,0
2962,COL make VAL CESSNA COL model VAL 402 COL seri...,COL make VAL CE COL model VAL 401 COL series V...,1,0.999301,0
3615,COL make VAL REARWIN COL model VAL 8500 COL se...,COL make VAL COMWTH COL model VAL 9000 COL ser...,0,0.999971,1
3899,COL make VAL HAWKER SIDDELEY COL model VAL HS1...,COL make VAL HS COL model VAL 125 COL series V...,1,0.558602,0

In [10]:
errors.to_csv("../aircraft_er_predictions/" + run_name + "_errors_review.csv", index=False)

In [11]:
def parse_record(record: str):
    """Parse Ditto serialized record into a dict of {field: value}."""
    parts = re.split(r"COL |VAL ", record.strip())
    parts = [p for p in parts if p]  # drop empties
    return {parts[i].strip(): parts[i+1].strip() for i in range(0, len(parts), 2)}

parsed = []

for _, row in errors.iterrows():
    left = parse_record(row["left"])
    right = parse_record(row["right"])
    parsed.append({
        "cictt_make": left.get("make"),
        "make": right.get("make"),
        "cictt_model": left.get("model"),
        "model": right.get("model"),
        "cictt_series": left.get("series"),
        "series": right.get("series"),
        "cictt_cert": left.get("cert"),
        "cert": right.get("cert"),
        "cictt_name": left.get("name"),
        "name": right.get("name"),
        "predicted": row["match"],
        "confidence": row["match_confidence"],
        "gold": row["gold"]
    })

aligned = pd.DataFrame(parsed)

In [12]:
aligned.to_csv("../aircraft_er_predictions/" + run_name + "_aligned_errors_review.csv", index=False)

In [13]:
aligned.head()

,cictt_make,make,cictt_model,model,cictt_series,series,cictt_cert,cert,cictt_name,name,predicted,confidence,gold
0,LEARJET,LR,35,35,A,35AC21A,A10CE,A10CE,No Popular Name,None,0,0.999731,1
1,BEECH,VERVLE,AT10,AT,AT10,AT,LTC-12,ATC323,WICHITA,None,1,0.998443,0
2,MITSUBISHI,MU,MU2B,2B,26A,20,NOT IDENTIFIED,A2PC,MARQUISE,None,1,0.999841,0
3,BELL,FEDRIC,UH1,UH34,E,E,H7SO,H7NM,IROQUOIS,None,1,0.870332,0
4,AERO DIFUSION,AMD,D1190,50,S,900,NOT CERTIFICATED,A46EU,COMPOSTELA,MYSTERE-FALCON,1,0.792658,0

### Top 1 Approach

Start with correct intuition. Understand the correct answer per row. Need the id as a primary key

In [14]:
# This has the left_ids and right_ids included
pairs_with_id_path = f"../data/ditto_aircraft/{run_name}/all_pairs_with_id.txt"
pairs_with_id = pd.read_csv(pairs_with_id_path)


df_all["left_id"] = pairs_with_id["left_id"] 
df_all["right_id"] = pairs_with_id["right_id"]

In [15]:
#Add primary key left_id and right_id from pairs_with_id file
df_all["left_id"] = pairs_with_id["left_id"] 
df_all["right_id"] = pairs_with_id["right_id"] 

#Analyze result for each row determining TPs, FPs, etc.
df_all["TP"] = ((df_all["match"] == 1) & (df_all["gold"] == 1)).astype(int)
df_all["TN"] = ((df_all["match"] == 0) & (df_all["gold"] == 0)).astype(int)
df_all["FP"] = ((df_all["match"] == 1) & (df_all["gold"] == 0)).astype(int)
df_all["FN"] = ((df_all["match"] == 0) & (df_all["gold"] == 1)).astype(int)

In [16]:
df_all.head()

,left,right,match,match_confidence,gold,left_id,right_id,TP,TN,FP,FN
0,COL make VAL GULFSTREAM COL model VAL GVI COL ...,COL make VAL PA COL model VAL 46 COL series VA...,0,0.999998,0,10257,2641,0,1,0,0
1,COL make VAL PIAGGIO COL model VAL P136 COL se...,COL make VAL BHT COL model VAL UH1E COL series...,0,0.999994,0,7344,586,0,1,0,0
2,COL make VAL AERONCA COL model VAL L3 COL seri...,COL make VAL LR COL model VAL 45 COL series VA...,0,0.999996,0,165,2223,0,1,0,0
3,COL make VAL PZL OKECIE COL model VAL PZL104 C...,COL make VAL B COL model VAL 737 COL series VA...,0,0.999995,0,7824,876,0,1,0,0
4,COL make VAL BEECH COL model VAL 99 COL series...,COL make VAL BE COL model VAL 18 COL series VA...,0,0.999997,0,1318,345,0,1,0,0

In [17]:
#For ech right_id, sum TPs, FPs, etc by right id

cols = ["TP", "FP", "TN", "FN"]

by_right = (
    df_all
      .groupby("right_id", as_index=False)[cols]
      .sum()
)

by_right

      right_id  TP  FP  TN  FN
0            1   1   0   7   0
1            2   1   0  12   0
2            3   1   0  14   0
3            4   1   0  12   0
4            5   1   0   9   0
...        ...  ..  ..  ..  ..
3673      3735   1   0   8   0
3674      3736   1   0  10   0
3675      3737   1   0  10   0
3676      3738   1   0   8   0
3677      3739   1   0   9   0

[3678 rows x 5 columns]

In [18]:
# Agregating by right_id shows stats for each right_id
df_agg_right = (
      df_all.groupby('right_id', as_index=False)
      .agg({'right':         'first',                          
            'TP':           'sum',
            'TN':           'sum',
            'FP':           'sum',
            'FN':           'sum',                    
            'left':        lambda s: pd.unique(s.dropna()).tolist(),
      })
)
df_agg_right["left_len"] = df_agg_right["left"].apply(len)

df_agg_right.head()

,right_id,right,TP,TN,FP,FN,left,left_len
0,1,COL make VAL AERPEG COL model VAL M100S COL se...,1,7,0,0,[COL make VAL BEECH COL model VAL SNB COL seri...,8
1,2,COL make VAL AL COL model VAL 60 COL series VA...,1,12,0,0,[COL make VAL SCHLEICHER COL model VAL ASW12 C...,13
2,3,COL make VAL AL COL model VAL 60 COL series VA...,1,14,0,0,[COL make VAL STAR COL model VAL CAVALIER COL ...,15
3,4,COL make VAL MRCHTI COL model VAL F260 COL ser...,1,12,0,0,[COL make VAL AERMACCHI COL model VAL F260 COL...,13
4,5,COL make VAL MRCHTI COL model VAL F260 COL ser...,1,9,0,0,[COL make VAL BOEING COL model VAL 737 COL ser...,10

In [19]:
# Calculate the maximum match confidence only for classified matches
df_agg_max_conf_right = (
      df_all[df_all["match"]==1].groupby('right_id', as_index=False)
      .agg({'match_confidence':         'max',
            'left_id':                  'min'                          
      })
)

In [20]:
df_agg_max_conf_right

      right_id  match_confidence  left_id
0            1          0.999267       25
1            2          0.999905       46
2            3          0.999919       47
3            4          0.999895       48
4            5          0.999888       49
...        ...               ...      ...
3661      3735          0.999893    24014
3662      3736          0.999883    24016
3663      3737          0.999862    24017
3664      3738          0.999482    24018
3665      3739          0.956797    25417

[3666 rows x 3 columns]

In [21]:
# Merge exhaustive right rows with merged right rows
df_all_merged_right = df_all.merge(
    df_agg_right,
    on="right_id",
    how="left",
    suffixes=("", "_agg"))

In [22]:
# Merge max match confidence score
df_all_merged_right = df_all_merged_right.merge(
    df_agg_max_conf_right,
    on="right_id",
    how="left",
    suffixes=("", "_maxmin"))

In [23]:
df_all_merged_right

,left,right,match,match_confidence,gold,left_id,right_id,TP,TN,FP,FN,right_agg,TP_agg,TN_agg,FP_agg,FN_agg,left_agg,left_len,match_confidence_maxmin,left_id_maxmin
0,COL make VAL GULFSTREAM COL model VAL GVI COL ...,COL make VAL PA COL model VAL 46 COL series VA...,0,0.999998,0,10257,2641,0,1,0,0,COL make VAL PA COL model VAL 46 COL series VA...,1,10,0,0,[COL make VAL GULFSTREAM COL model VAL GVI COL...,11,0.999846,7632.0
1,COL make VAL PIAGGIO COL model VAL P136 COL se...,COL make VAL BHT COL model VAL UH1E COL series...,0,0.999994,0,7344,586,0,1,0,0,COL make VAL BHT COL model VAL UH1E COL series...,1,9,0,0,[COL make VAL PIAGGIO COL model VAL P136 COL s...,10,0.999867,1513.0
2,COL make VAL AERONCA COL model VAL L3 COL seri...,COL make VAL LR COL model VAL 45 COL series VA...,0,0.999996,0,165,2223,0,1,0,0,COL make VAL LR COL model VAL 45 COL series VA...,1,12,0,0,[COL make VAL AERONCA COL model VAL L3 COL ser...,13,0.999874,6355.0
3,COL make VAL PZL OKECIE COL model VAL PZL104 C...,COL make VAL B COL model VAL 737 COL series VA...,0,0.999995,0,7824,876,0,1,0,0,COL make VAL B COL model VAL 737 COL series VA...,1,8,0,0,[COL make VAL PZL OKECIE COL model VAL PZL104 ...,9,0.999792,2078.0
4,COL make VAL BEECH COL model VAL 99 COL series...,COL make VAL BE COL model VAL 18 COL series VA...,0,0.999997,0,1318,345,0,1,0,0,COL make VAL BE COL model VAL 18 COL series VA...,1,8,0,0,[COL make VAL BEECH COL model VAL 99 COL serie...,9,0.999921,1151.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40383,COL make VAL NORTH AMERICAN COL model VAL B25 ...,COL model VAL B25 COL series VAL J COL cert VA...,1,0.999870,1,7173,2438,1,0,0,0,COL model VAL B25 COL series VAL J COL cert VA...,1,15,0,0,[COL make VAL SIKORSKY COL model VAL S76 COL s...,16,0.999870,7173.0
40384,COL make VAL BEECH COL model VAL 17 COL series...,COL make VAL AYRES COL model VAL S2 COL series...,0,0.999997,0,1129,256,0,1,0,0,COL make VAL AYRES COL model VAL S2 COL series...,1,12,0,0,[COL make VAL PITTS COL model VAL S1 COL serie...,13,0.999890,862.0
40385,COL make VAL CURTISS WRIGHT COL model VAL 22 C...,COL make VAL FIREFLY COL model VAL 5 COL serie...,0,0.999996,0,23805,309,0,1,0,0,COL make VAL FIREFLY COL model VAL 5 COL serie...,1,9,0,0,[COL make VAL BOEING COL model VAL 777 COL ser...,10,0.999878,1065.0
40386,COL make VAL MAULE COL model VAL M6 COL series...,COL make VAL M COL model VAL 6 COL series VAL ...,1,0.999911,1,6732,2316,1,0,0,0,COL make VAL M COL model VAL 6 COL series VAL ...,1,12,0,0,[COL make VAL NORTH AMERICAN COL model VAL P51...,13,0.999911,6732.0
40387,COL make VAL HILLER COL model VAL UH12 COL ser...,COL make VAL NAVION COL model VAL NAVION COL s...,0,0.999996,0,5816,2420,0,1,0,0,COL make VAL NAVION COL model VAL NAVION COL s...,1,12,0,0,[COL make VAL AERO COMMANDER COL model VAL 681...,13,0.999918,7105.0

In [24]:
# A best (top 1) match is when there is a match and the match has the maximum confidence
df_all_merged_right["best"] = ((df_all_merged_right["match"]==1) & (df_all_merged_right["match_confidence"] == df_all_merged_right["match_confidence_maxmin"]) & (df_all_merged_right["left_id"] == df_all_merged_right["left_id_maxmin"])).astype(int)

In [25]:
#Check that each right_id has one best match
df_all_merged_right[df_all_merged_right["best"] == 1]["right_id"].value_counts()

right_id
2316    1
895     1
2476    1
1264    1
3243    1
       ..
873     1
143     1
832     1
3133    1
2760    1
Name: count, Length: 3660, dtype: int64

In [26]:
#All Data -compare best match (top 1) with gold

y_true = df_all_merged_right["gold"]
y_pred = df_all_merged_right["best"]

print("Accuracy:", accuracy_score(y_true, y_pred))
print("\nClassification report:\n", classification_report(y_true, y_pred,digits=3))
print("\nConfusion matrix:\n", confusion_matrix(y_true, y_pred))

Accuracy: 0.9995543230662574

Classification report:
               precision    recall  f1-score   support

           0      1.000     1.000     1.000     36710
           1      1.000     0.995     0.998      3678

    accuracy                          1.000     40388
   macro avg      1.000     0.998     0.999     40388
weighted avg      1.000     1.000     1.000     40388


Confusion matrix:
 [[36710     0]
 [   18  3660]]

In [27]:
right_errors = df_all_merged_right[df_all_merged_right["gold"] != df_all_merged_right["best"]]

In [28]:
right_errors

,left,right,match,match_confidence,gold,left_id,right_id,TP,TN,FP,...,right_agg,TP_agg,TN_agg,FP_agg,FN_agg,left_agg,left_len,match_confidence_maxmin,left_id_maxmin,best
2806,COL make VAL CALLAIR COL model VAL A9 COL seri...,COL make VAL CALAIR COL model VAL A COL series...,1,0.999899,1,3108,1205,1,0,0,...,COL make VAL CALAIR COL model VAL A COL series...,1,12,1,0,[COL make VAL BOEING COL model VAL 767 COL ser...,14,0.999899,3103.0,0
12637,COL make VAL WACO COL model VAL ZGC COL series...,COL make VAL WACO COL model VAL ZGC COL series...,1,0.999910,1,9551,3117,1,0,0,...,COL make VAL WACO COL model VAL ZGC COL series...,1,11,1,0,[COL make VAL PILATUS COL model VAL PC6 COL se...,13,0.999910,4047.0,0
14309,COL make VAL VERVILLE COL model VAL AT COL ser...,COL make VAL VERVLE COL model VAL AT COL serie...,1,0.999878,1,23794,3726,1,0,0,...,COL make VAL VERVLE COL model VAL AT COL serie...,1,11,1,0,[COL make VAL HEATH COL model VAL LNB4 COL ser...,13,0.999878,23624.0,0
19342,COL make VAL HAWKER SIDDELEY COL model VAL HS1...,COL make VAL HS COL model VAL 125 COL series V...,1,0.999909,1,11405,504,1,0,0,...,COL make VAL HS COL model VAL 125 COL series V...,1,8,1,0,[COL make VAL CESSNA COL model VAL 337 COL ser...,10,0.999909,5718.0,0
21300,COL make VAL SIKORSKY COL model VAL UH34 COL s...,COL make VAL FEDRIC COL model VAL UH34 COL ser...,1,0.999917,1,21643,3592,1,0,0,...,COL make VAL FEDRIC COL model VAL UH34 COL ser...,1,11,1,0,[COL make VAL WACO COL model VAL YQC COL serie...,13,0.999917,12561.0,0
32479,COL make VAL COMMAND AIRE COL model VAL 3C3 CO...,COL make VAL COAIRE COL model VAL 3C COL serie...,0,0.875757,1,4296,1604,0,0,0,...,COL make VAL COAIRE COL model VAL 3C COL serie...,0,6,0,1,[COL make VAL BOEING COL model VAL 727 COL ser...,7,NaN,NaN,0
32480,COL make VAL GRUMMAN COL model VAL OV1 COL ser...,COL make VAL OW COL model VAL 5M COL series VA...,0,0.999996,1,16409,3440,0,0,0,...,COL make VAL OW COL model VAL 5M COL series VA...,0,12,0,1,[COL make VAL BEECH COL model VAL 35 COL serie...,13,NaN,NaN,0
32532,COL make VAL GULFSTREAM COL model VAL GULFSTRE...,COL make VAL IA COL model VAL ASTRA COL series...,0,0.999996,1,5617,2080,0,0,0,...,COL make VAL IA COL model VAL ASTRA COL series...,0,10,0,1,[COL make VAL GULFSTREAM COL model VAL GIV COL...,11,NaN,NaN,0
33999,COL make VAL BOEING COL model VAL 707 COL seri...,COL make VAL B COL model VAL 707 COL series VA...,0,0.999986,1,1618,655,0,0,0,...,COL make VAL B COL model VAL 707 COL series VA...,0,6,0,1,[COL make VAL PIPER COL model VAL PA60 COL ser...,7,NaN,NaN,0
34257,COL make VAL CONVAIR COL model VAL 640 COL ser...,COL make VAL CV COL model VAL 340 COL series V...,0,0.999605,1,4347,1651,0,0,0,...,COL make VAL CV COL model VAL 340 COL series V...,0,9,0,1,[COL make VAL KUBICEK COL model VAL BB30 COL s...,10,NaN,NaN,0
34874,COL make VAL BOEING COL model VAL 737 COL seri...,COL make VAL B COL model VAL 737 COL series VA...,0,0.999953,1,2170,903,0,0,0,...,COL make VAL B COL model VAL 737 COL series VA...,0,3,0,1,[COL make VAL DOUGLAS COL model VAL DC6 COL se...,4,NaN,NaN,0
34997,COL make VAL BOEING COL model VAL 737 COL seri...,COL make VAL B COL model VAL 737 COL series VA...,0,0.999984,1,2291,951,0,0,0,...,COL make VAL B COL model VAL 737 COL series VA...,0,8,0,1,[COL make VAL BELL COL model VAL P39 COL serie...,9,NaN,NaN,0
35005,COL make VAL BOEING COL model VAL 737 COL seri...,COL make VAL B COL model VAL 737 COL series VA...,0,0.970095,1,10220,3157,0,0,0,...,COL make VAL B COL model VAL 737 COL series VA...,0,9,0,1,[COL make VAL AEROSPATIALE COL model VAL AS350...,10,NaN,NaN,0
35068,COL make VAL STINSON COL model VAL SM2 COL ser...,COL make VAL SM COL model VAL 2 COL series VAL...,1,0.999913,1,22173,3668,1,0,0,...,COL make VAL SM COL model VAL 2 COL series VAL...,1,9,1,0,[COL make VAL REARWIN COL model VAL 3000 COL s...,11,0.999913,539.0,0
35381,COL make VAL LOCKHEED COL model VAL F5 COL ser...,COL make VAL P COL model VAL 38 COL series VAL...,0,0.999919,1,6582,2276,0,0,0,...,COL make VAL P COL model VAL 38 COL series VAL...,0,6,0,1,[COL make VAL VERTOL COL model VAL CH47 COL se...,7,NaN,NaN,0
36000,COL make VAL BEECH COL model VAL 17 COL series...,COL make VAL BE COL model VAL 17 COL series VA...,0,0.817679,1,1124,329,0,0,0,...,COL make VAL BE COL model VAL 17 COL series VA...,0,15,0,1,[COL make VAL BELL COL model VAL UH1 COL serie...,16,NaN,NaN,0
36988,COL make VAL LEARJET COL model VAL 35 COL seri...,COL make VAL LR COL model VAL 35 COL series VA...,0,0.999731,1,6351,2218,0,0,0,...,COL make VAL LR COL model VAL 35 COL series VA...,0,10,0,1,[COL make VAL BOEING COL model VAL 737 COL ser...,11,NaN,NaN,0
39960,COL make VAL REARWIN COL model VAL 8500 COL se...,COL make VAL COMWTH COL model VAL 9000 COL ser...,0,0.999971,1,7939,2699,0,0,0,...,COL make VAL COMWTH COL model VAL 9000 COL ser...,0,7,0,1,[COL make VAL CESSNA COL model VAL 305 COL ser...,8,NaN,NaN,0

In [29]:
cand = df_all[df_all["match"] == 1].sort_values("match_confidence", ascending=False)
best = cand.drop_duplicates(subset=["right_id"], keep="first")

# Evaluate links (recordlinkage-style)
true_links = set(df_all.loc[df_all["gold"]==1, ["left_id","right_id"]].itertuples(index=False, name=None))
pred_links = set(best[["left_id","right_id"]].itertuples(index=False, name=None))

tp = len(pred_links & true_links)
n_pred = len(pred_links)
n_true = len(true_links)
fp = n_pred - tp
fn = n_true - tp
coverage = n_pred / n_true

precision = tp / n_pred if n_pred else 0.0
recall = tp / n_true if n_true else 0.0
f1 = (2*precision*recall/(precision+recall)) if (precision+recall) else 0.0

print({"precision":precision, "recall":recall, "f1":f1, "coverage":coverage, "TP":tp, "FP":fp, "FN":fn, "n_pred":n_pred})

{'precision': 1.0, 'recall': 0.9967373572593801, 'f1': 0.9983660130718954, 'coverage': 0.9967373572593801, 'TP': 3666, 'FP': 0, 'FN': 12, 'n_pred': 3666}

In [30]:
print("unique left ids: ", best["left_id"].nunique(), " unique right ids: ", best["left_id"].nunique())
print("unique left ids: ", df_all["left_id"].nunique(), " unique right ids: ", df_all["left_id"].nunique())

unique left ids:  3451  unique right ids:  3451
unique left ids:  3456  unique right ids:  3456

In [31]:
df_all["left_id"].value_counts()

left_id
5382    60
1512    50
1514    48
6818    43
7552    43
        ..
3808     3
1635     3
8271     3
2129     3
1868     2
Name: count, Length: 3456, dtype: int64

### Repeat process by left_id - currently not working

In [32]:

df_agg_cictt = (
      df_all.groupby('left_id', as_index=False)
      .agg({'left':         'first',                          
            'TP':           'sum',
            'TN':           'sum',
            'FP':           'sum',
            'FN':           'sum',                    
            'right':        lambda s: pd.unique(s.dropna()).tolist(),

      })
)
df_agg_cictt["right_len"] = df_agg_cictt["right"].apply(len)

df_agg_cictt.head()

,left_id,left,TP,TN,FP,FN,right,right_len
0,25,COL make VAL AER PEGASO COL model VAL M100 COL...,1,11,0,0,[COL make VAL SCHLER COL model VAL ASW27 COL s...,12
1,46,COL make VAL AERMACCHI COL model VAL AL60 COL ...,1,13,0,0,[COL make VAL BB COL model VAL 22 COL series V...,14
2,47,COL make VAL AERMACCHI COL model VAL AL60 COL ...,1,10,0,0,[COL make VAL B COL model VAL 737 COL series V...,11
3,48,COL make VAL AERMACCHI COL model VAL F260 COL ...,1,8,0,0,[COL make VAL MRCHTI COL model VAL F260 COL se...,9
4,49,COL make VAL AERMACCHI COL model VAL F260 COL ...,1,9,0,0,[COL make VAL GROB COL model VAL G103 COL seri...,10

In [33]:
df_agg_max_conf = (
      df_all[df_all["match"]==1].groupby('left_id', as_index=False)
      .agg({'match_confidence':         'max',                          
      })
)
df_agg_max_conf["max_conf_match"] = df_agg_max_conf["match_confidence"]

df_agg_max_conf

      left_id  match_confidence  max_conf_match
0          25          0.999267        0.999267
1          46          0.999905        0.999905
2          47          0.999919        0.999919
3          48          0.999895        0.999895
4          49          0.999888        0.999888
...       ...               ...             ...
3446    25445          0.999879        0.999879
3447    25560          0.999897        0.999897
3448    25589          0.999892        0.999892
3449    25626          0.999833        0.999833
3450    25973          0.999743        0.999743

[3451 rows x 3 columns]

In [34]:
df_all_merged = df_all.merge(
    df_agg_cictt,
    on="left_id",
    how="left",
    suffixes=("", "_agg"))

In [35]:
df_all_merged = df_all_merged.merge(
    df_agg_max_conf,
    on="left_id",
    how="left",
    suffixes=("", "_max"))

In [36]:

df_all_merged["best"] = ((df_all_merged["match"]==1) & (df_all_merged["match_confidence"] == df_all_merged["match_confidence_max"])).astype(int)

In [37]:
df_all_merged

,left,right,match,match_confidence,gold,left_id,right_id,TP,TN,FP,...,left_agg,TP_agg,TN_agg,FP_agg,FN_agg,right_agg,right_len,match_confidence_max,max_conf_match,best
0,COL make VAL GULFSTREAM COL model VAL GVI COL ...,COL make VAL PA COL model VAL 46 COL series VA...,0,0.999998,0,10257,2641,0,1,0,...,COL make VAL GULFSTREAM COL model VAL GVI COL ...,2,22,0,0,[COL make VAL PA COL model VAL 46 COL series V...,24,0.999907,0.999907,0
1,COL make VAL PIAGGIO COL model VAL P136 COL se...,COL make VAL BHT COL model VAL UH1E COL series...,0,0.999994,0,7344,586,0,1,0,...,COL make VAL PIAGGIO COL model VAL P136 COL se...,1,13,0,0,[COL make VAL BHT COL model VAL UH1E COL serie...,14,0.999914,0.999914,0
2,COL make VAL AERONCA COL model VAL L3 COL seri...,COL make VAL LR COL model VAL 45 COL series VA...,0,0.999996,0,165,2223,0,1,0,...,COL make VAL AERONCA COL model VAL L3 COL seri...,1,8,0,0,[COL make VAL LR COL model VAL 45 COL series V...,9,0.999888,0.999888,0
3,COL make VAL PZL OKECIE COL model VAL PZL104 C...,COL make VAL B COL model VAL 737 COL series VA...,0,0.999995,0,7824,876,0,1,0,...,COL make VAL PZL OKECIE COL model VAL PZL104 C...,1,13,0,0,[COL make VAL B COL model VAL 737 COL series V...,14,0.999797,0.999797,0
4,COL make VAL BEECH COL model VAL 99 COL series...,COL make VAL BE COL model VAL 18 COL series VA...,0,0.999997,0,1318,345,0,1,0,...,COL make VAL BEECH COL model VAL 99 COL series...,1,11,0,0,[COL make VAL BE COL model VAL 18 COL series V...,12,0.999904,0.999904,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40383,COL make VAL NORTH AMERICAN COL model VAL B25 ...,COL model VAL B25 COL series VAL J COL cert VA...,1,0.999870,1,7173,2438,1,0,0,...,COL make VAL NORTH AMERICAN COL model VAL B25 ...,1,10,0,0,[COL make VAL BHT COL model VAL 210 COL series...,11,0.999870,0.999870,1
40384,COL make VAL BEECH COL model VAL 17 COL series...,COL make VAL AYRES COL model VAL S2 COL series...,0,0.999997,0,1129,256,0,1,0,...,COL make VAL BEECH COL model VAL 17 COL series...,1,14,0,0,[COL make VAL DGA COL model VAL 15 COL series ...,15,0.999915,0.999915,0
40385,COL make VAL CURTISS WRIGHT COL model VAL 22 C...,COL make VAL FIREFLY COL model VAL 5 COL serie...,0,0.999996,0,23805,309,0,1,0,...,COL make VAL CURTISS WRIGHT COL model VAL 22 C...,1,15,0,0,[COL make VAL CV COL model VAL 340 COL series ...,16,0.999895,0.999895,0
40386,COL make VAL MAULE COL model VAL M6 COL series...,COL make VAL M COL model VAL 6 COL series VAL ...,1,0.999911,1,6732,2316,1,0,0,...,COL make VAL MAULE COL model VAL M6 COL series...,1,7,0,0,[COL make VAL B COL model VAL 737 COL series V...,8,0.999911,0.999911,1
40387,COL make VAL HILLER COL model VAL UH12 COL ser...,COL make VAL NAVION COL model VAL NAVION COL s...,0,0.999996,0,5816,2420,0,1,0,...,COL make VAL HILLER COL model VAL UH12 COL ser...,1,9,1,0,[COL make VAL L COL model VAL 1049 COL series ...,11,0.999903,0.999903,0

In [38]:
df_all_merged[df_all_merged["best"]==1]

,left,right,match,match_confidence,gold,left_id,right_id,TP,TN,FP,...,left_agg,TP_agg,TN_agg,FP_agg,FN_agg,right_agg,right_len,match_confidence_max,max_conf_match,best
6,COL make VAL BOEING COL model VAL 737 COL seri...,COL make VAL B COL model VAL 737 COL series VA...,1,0.999886,1,2140,895,1,0,0,...,COL make VAL BOEING COL model VAL 737 COL seri...,1,7,0,0,[COL make VAL B COL model VAL 737 COL series V...,8,0.999886,0.999886,1
7,COL make VAL PIAGGIO COL model VAL P136 COL se...,COL make VAL P COL model VAL 136 COL series VA...,1,0.999916,1,7345,2476,1,0,0,...,COL make VAL PIAGGIO COL model VAL P136 COL se...,1,13,0,0,[COL make VAL P COL model VAL 136 COL series V...,14,0.999916,0.999916,1
19,COL make VAL CESSNA COL model VAL 172 COL seri...,COL make VAL CE COL model VAL 172 COL series V...,1,0.999901,1,3679,1264,1,0,0,...,COL make VAL CESSNA COL model VAL 172 COL seri...,1,10,0,0,[COL make VAL CE COL model VAL 172 COL series ...,11,0.999901,0.999901,1
27,COL make VAL PILATUS COL model VAL PC6 COL ser...,COL make VAL PC COL model VAL 6 COL series VAL...,1,0.999872,1,11251,3243,1,0,0,...,COL make VAL PILATUS COL model VAL PC6 COL ser...,2,27,0,0,[COL make VAL PC COL model VAL 6 COL series VA...,29,0.999872,0.999872,1
35,COL make VAL PIPER COL model VAL L18 COL serie...,COL make VAL PA COL model VAL 19 COL series VA...,1,0.999812,1,7478,2526,1,0,0,...,COL make VAL PIPER COL model VAL L18 COL serie...,1,7,0,0,[COL make VAL PA COL model VAL 19 COL series V...,8,0.999812,0.999812,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40361,COL make VAL BOEING COL model VAL 737 COL seri...,COL make VAL B COL model VAL 737 COL series VA...,1,0.999901,1,1942,809,1,0,0,...,COL make VAL BOEING COL model VAL 737 COL seri...,1,10,0,0,[COL make VAL VARGA COL model VAL 2150 COL ser...,11,0.999901,0.999901,1
40374,COL make VAL AGUSTA COL model VAL AW139 COL se...,COL make VAL AGUSTA COL model VAL AW139 COL se...,1,0.999902,1,339,158,1,0,0,...,COL make VAL AGUSTA COL model VAL AW139 COL se...,1,12,0,0,[COL make VAL TCRAFT COL model VAL 22 COL seri...,13,0.999902,0.999902,1
40379,COL make VAL COMMAND AIRE COL model VAL 5C3 CO...,COL make VAL COAIRE COL model VAL 5C COL serie...,1,0.943862,1,21931,3620,1,0,0,...,COL make VAL COMMAND AIRE COL model VAL 5C3 CO...,1,15,0,0,[COL make VAL ENSTRM COL model VAL F28 COL ser...,16,0.943862,0.943862,1
40383,COL make VAL NORTH AMERICAN COL model VAL B25 ...,COL model VAL B25 COL series VAL J COL cert VA...,1,0.999870,1,7173,2438,1,0,0,...,COL make VAL NORTH AMERICAN COL model VAL B25 ...,1,10,0,0,[COL make VAL BHT COL model VAL 210 COL series...,11,0.999870,0.999870,1
40386,COL make VAL MAULE COL model VAL M6 COL series...,COL make VAL M COL model VAL 6 COL series VAL ...,1,0.999911,1,6732,2316,1,0,0,...,COL make VAL MAULE COL model VAL M6 COL series...,1,7,0,0,[COL make VAL B COL model VAL 737 COL series V...,8,0.999911,0.999911,1

In [39]:
df_all_merged[df_all_merged["best"] == 1]["left_id"].value_counts()

left_id
6732     1
2140     1
7345     1
3679     1
11251    1
        ..
2069     1
293      1
1997     1
9658     1
8169     1
Name: count, Length: 3451, dtype: int64

In [40]:
df_all_merged["left_id"].value_counts()

left_id
5382    60
1512    50
1514    48
6818    43
7552    43
        ..
3808     3
1635     3
8271     3
2129     3
1868     2
Name: count, Length: 3456, dtype: int64